/* tslint:disable */
/* eslint-disable */
/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchedWebstreamMetadata
 */
export interface PatchedWebstreamMetadata {
    /**
     * 
     * @type {string}
     * @memberof PatchedWebstreamMetadata
     */
    'item_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedWebstreamMetadata
     */
    'starts_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedWebstreamMetadata
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedWebstreamMetadata
     */
    'schedule'?: string;
}

