/* tslint:disable */
/* eslint-disable */
/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchedPlaylistContent
 */
export interface PatchedPlaylistContent {
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'item_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlaylistContent
     */
    'stream_id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlaylistContent
     */
    'type'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlaylistContent
     */
    'position'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedPlaylistContent
     */
    'trackoffset'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'cliplength'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'cuein'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'cueout'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'fadein'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'fadeout'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'playlist'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'file'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPlaylistContent
     */
    'block'?: string | null;
}

