/* tslint:disable */
/* eslint-disable */
/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchedShowInstance
 */
export interface PatchedShowInstance {
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'item_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedShowInstance
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'starts'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'ends'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedShowInstance
     */
    'record'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedShowInstance
     */
    'rebroadcast'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'time_filled'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'last_scheduled'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedShowInstance
     */
    'modified_instance'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedShowInstance
     */
    'autoplaylist_built'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'show'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedShowInstance
     */
    'show_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'instance'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowInstance
     */
    'file'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedShowInstance
     */
    'file_id'?: number;
}

