/* tslint:disable */
/* eslint-disable */
/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchedShowRebroadcast
 */
export interface PatchedShowRebroadcast {
    /**
     * 
     * @type {number}
     * @memberof PatchedShowRebroadcast
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowRebroadcast
     */
    'day_offset'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedShowRebroadcast
     */
    'start_time'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedShowRebroadcast
     */
    'show'?: number;
}

