/* tslint:disable */
/* eslint-disable */
/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchedPodcast
 */
export interface PatchedPodcast {
    /**
     * 
     * @type {number}
     * @memberof PatchedPodcast
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'creator'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'language'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'copyright'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'link'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'itunes_author'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'itunes_keywords'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'itunes_summary'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'itunes_subtitle'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'itunes_category'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedPodcast
     */
    'itunes_explicit'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedPodcast
     */
    'owner'?: number | null;
}

