/* tslint:disable */
/* eslint-disable */
/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlayoutHistoryTemplate
 */
export interface PlayoutHistoryTemplate {
    /**
     * 
     * @type {string}
     * @memberof PlayoutHistoryTemplate
     */
    'item_url': string;
    /**
     * 
     * @type {string}
     * @memberof PlayoutHistoryTemplate
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PlayoutHistoryTemplate
     */
    'type': string;
}

