/* tslint:disable */
/* eslint-disable */
/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebstreamMetadata
 */
export interface WebstreamMetadata {
    /**
     * 
     * @type {string}
     * @memberof WebstreamMetadata
     */
    'item_url': string;
    /**
     * 
     * @type {string}
     * @memberof WebstreamMetadata
     */
    'start_time': string;
    /**
     * 
     * @type {string}
     * @memberof WebstreamMetadata
     */
    'liquidsoap_data': string;
    /**
     * 
     * @type {string}
     * @memberof WebstreamMetadata
     */
    'instance': string;
}

