/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedCloudFile model module.
 * @module model/PatchedCloudFile
 * @version 2.0.0
 */
class PatchedCloudFile {
    /**
     * Constructs a new <code>PatchedCloudFile</code>.
     * @alias module:model/PatchedCloudFile
     */
    constructor() { 
        
        PatchedCloudFile.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedCloudFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedCloudFile} obj Optional instance to populate.
     * @return {module:model/PatchedCloudFile} The populated <code>PatchedCloudFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedCloudFile();

            if (data.hasOwnProperty('item_url')) {
                obj['item_url'] = ApiClient.convertToType(data['item_url'], 'String');
            }
            if (data.hasOwnProperty('storage_backend')) {
                obj['storage_backend'] = ApiClient.convertToType(data['storage_backend'], 'String');
            }
            if (data.hasOwnProperty('resource_id')) {
                obj['resource_id'] = ApiClient.convertToType(data['resource_id'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} item_url
 */
PatchedCloudFile.prototype['item_url'] = undefined;

/**
 * @member {String} storage_backend
 */
PatchedCloudFile.prototype['storage_backend'] = undefined;

/**
 * @member {String} resource_id
 */
PatchedCloudFile.prototype['resource_id'] = undefined;

/**
 * @member {String} filename
 */
PatchedCloudFile.prototype['filename'] = undefined;






export default PatchedCloudFile;

