# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import libretime_client
from libretime_client.model.show_days import ShowDays
from libretime_client import configuration


class TestShowDays(unittest.TestCase):
    """ShowDays unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
