# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from libretime_client.paths.api_v2_playout_history.post import PlayoutHistoryCreate
from libretime_client.paths.api_v2_playout_history_id.delete import PlayoutHistoryDestroy
from libretime_client.paths.api_v2_playout_history.get import PlayoutHistoryList
from libretime_client.paths.api_v2_playout_history_id.patch import PlayoutHistoryPartialUpdate
from libretime_client.paths.api_v2_playout_history_id.get import PlayoutHistoryRetrieve
from libretime_client.paths.api_v2_playout_history_id.put import PlayoutHistoryUpdate


class PlayoutHistoryApi(
    PlayoutHistoryCreate,
    PlayoutHistoryDestroy,
    PlayoutHistoryList,
    PlayoutHistoryPartialUpdate,
    PlayoutHistoryRetrieve,
    PlayoutHistoryUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
