# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from libretime_client.paths.api_v2_podcasts.post import PodcastsCreate
from libretime_client.paths.api_v2_podcasts_id.delete import PodcastsDestroy
from libretime_client.paths.api_v2_podcasts.get import PodcastsList
from libretime_client.paths.api_v2_podcasts_id.patch import PodcastsPartialUpdate
from libretime_client.paths.api_v2_podcasts_id.get import PodcastsRetrieve
from libretime_client.paths.api_v2_podcasts_id.put import PodcastsUpdate


class PodcastsApi(
    PodcastsCreate,
    PodcastsDestroy,
    PodcastsList,
    PodcastsPartialUpdate,
    PodcastsRetrieve,
    PodcastsUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
