# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from libretime_client.paths.api_v2_show_days.post import ShowDaysCreate
from libretime_client.paths.api_v2_show_days_id.delete import ShowDaysDestroy
from libretime_client.paths.api_v2_show_days.get import ShowDaysList
from libretime_client.paths.api_v2_show_days_id.patch import ShowDaysPartialUpdate
from libretime_client.paths.api_v2_show_days_id.get import ShowDaysRetrieve
from libretime_client.paths.api_v2_show_days_id.put import ShowDaysUpdate


class ShowDaysApi(
    ShowDaysCreate,
    ShowDaysDestroy,
    ShowDaysList,
    ShowDaysPartialUpdate,
    ShowDaysRetrieve,
    ShowDaysUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
