# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from libretime_client.paths.api_v2_station_podcasts.post import StationPodcastsCreate
from libretime_client.paths.api_v2_station_podcasts_id.delete import StationPodcastsDestroy
from libretime_client.paths.api_v2_station_podcasts.get import StationPodcastsList
from libretime_client.paths.api_v2_station_podcasts_id.patch import StationPodcastsPartialUpdate
from libretime_client.paths.api_v2_station_podcasts_id.get import StationPodcastsRetrieve
from libretime_client.paths.api_v2_station_podcasts_id.put import StationPodcastsUpdate


class StationPodcastsApi(
    StationPodcastsCreate,
    StationPodcastsDestroy,
    StationPodcastsList,
    StationPodcastsPartialUpdate,
    StationPodcastsRetrieve,
    StationPodcastsUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
