# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from libretime_client.paths.api_v2_webstreams.post import WebstreamsCreate
from libretime_client.paths.api_v2_webstreams_id.delete import WebstreamsDestroy
from libretime_client.paths.api_v2_webstreams.get import WebstreamsList
from libretime_client.paths.api_v2_webstreams_id.patch import WebstreamsPartialUpdate
from libretime_client.paths.api_v2_webstreams_id.get import WebstreamsRetrieve
from libretime_client.paths.api_v2_webstreams_id.put import WebstreamsUpdate


class WebstreamsApi(
    WebstreamsCreate,
    WebstreamsDestroy,
    WebstreamsList,
    WebstreamsPartialUpdate,
    WebstreamsRetrieve,
    WebstreamsUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
