/**
 * LibreTime API
 * Radio Broadcast & Automation Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LibreTimeApi);
  }
}(this, function(expect, LibreTimeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LibreTimeApi.PatchedPlaylistContent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PatchedPlaylistContent', function() {
    it('should create an instance of PatchedPlaylistContent', function() {
      // uncomment below and update the code to test PatchedPlaylistContent
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be.a(LibreTimeApi.PatchedPlaylistContent);
    });

    it('should have the property itemUrl (base name: "item_url")', function() {
      // uncomment below and update the code to test the property itemUrl
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property streamId (base name: "stream_id")', function() {
      // uncomment below and update the code to test the property streamId
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property trackoffset (base name: "trackoffset")', function() {
      // uncomment below and update the code to test the property trackoffset
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property cliplength (base name: "cliplength")', function() {
      // uncomment below and update the code to test the property cliplength
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property cuein (base name: "cuein")', function() {
      // uncomment below and update the code to test the property cuein
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property cueout (base name: "cueout")', function() {
      // uncomment below and update the code to test the property cueout
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property fadein (base name: "fadein")', function() {
      // uncomment below and update the code to test the property fadein
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property fadeout (base name: "fadeout")', function() {
      // uncomment below and update the code to test the property fadeout
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property playlist (base name: "playlist")', function() {
      // uncomment below and update the code to test the property playlist
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

    it('should have the property block (base name: "block")', function() {
      // uncomment below and update the code to test the property block
      //var instance = new LibreTimeApi.PatchedPlaylistContent();
      //expect(instance).to.be();
    });

  });

}));
