# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from libretime_client.api.celery_tasks_api import CeleryTasksApi  # noqa: E501


class TestCeleryTasksApi(unittest.TestCase):
    """CeleryTasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CeleryTasksApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_celery_tasks_create(self) -> None:
        """Test case for celery_tasks_create

        """
        pass

    def test_celery_tasks_destroy(self) -> None:
        """Test case for celery_tasks_destroy

        """
        pass

    def test_celery_tasks_list(self) -> None:
        """Test case for celery_tasks_list

        """
        pass

    def test_celery_tasks_partial_update(self) -> None:
        """Test case for celery_tasks_partial_update

        """
        pass

    def test_celery_tasks_retrieve(self) -> None:
        """Test case for celery_tasks_retrieve

        """
        pass

    def test_celery_tasks_update(self) -> None:
        """Test case for celery_tasks_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
