"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.patched_third_party_track_reference import PatchedThirdPartyTrackReference


class TestPatchedThirdPartyTrackReference(unittest.TestCase):
    """PatchedThirdPartyTrackReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedThirdPartyTrackReference(self):
        """Test PatchedThirdPartyTrackReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedThirdPartyTrackReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
