"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import libretime_client
from libretime_client.api.sessions_api import SessionsApi  # noqa: E501


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self):
        self.api = SessionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sessions_create(self):
        """Test case for sessions_create

        """
        pass

    def test_sessions_destroy(self):
        """Test case for sessions_destroy

        """
        pass

    def test_sessions_list(self):
        """Test case for sessions_list

        """
        pass

    def test_sessions_partial_update(self):
        """Test case for sessions_partial_update

        """
        pass

    def test_sessions_retrieve(self):
        """Test case for sessions_retrieve

        """
        pass

    def test_sessions_update(self):
        """Test case for sessions_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
