# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from libretime_client.models.record_enabled_enum import RecordEnabledEnum  # noqa: E501

class TestRecordEnabledEnum(unittest.TestCase):
    """RecordEnabledEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordEnabledEnum(self):
        """Test RecordEnabledEnum"""
        # inst = RecordEnabledEnum()

if __name__ == '__main__':
    unittest.main()
