"""
    LibreTime API

    Radio Broadcast & Automation Platform  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import libretime_client
from libretime_client.model.patched_live_log import PatchedLiveLog


class TestPatchedLiveLog(unittest.TestCase):
    """PatchedLiveLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedLiveLog(self):
        """Test PatchedLiveLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedLiveLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
