# coding: utf-8

"""
    LibreTime API

    Radio Broadcast & Automation Platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from libretime_client.api.login_attempts_api import LoginAttemptsApi  # noqa: E501


class TestLoginAttemptsApi(unittest.TestCase):
    """LoginAttemptsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoginAttemptsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_login_attempts_create(self) -> None:
        """Test case for login_attempts_create

        """
        pass

    def test_login_attempts_destroy(self) -> None:
        """Test case for login_attempts_destroy

        """
        pass

    def test_login_attempts_list(self) -> None:
        """Test case for login_attempts_list

        """
        pass

    def test_login_attempts_partial_update(self) -> None:
        """Test case for login_attempts_partial_update

        """
        pass

    def test_login_attempts_retrieve(self) -> None:
        """Test case for login_attempts_retrieve

        """
        pass

    def test_login_attempts_update(self) -> None:
        """Test case for login_attempts_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
